---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову.
  - Пользователь должен иметь возможность выбирать категорию товаров.
  - Пользователь должен иметь возможность фильтровать товары по цене.
  - Пользователь должен иметь возможность фильтровать товары по производителю.
  - Пользователь должен иметь возможность фильтровать товары по наличию.
  - Пользователь должен иметь возможность просматривать каталог товаров.
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен иметь десктопную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность зарегестрироваться и авторизоваться.
  - Пользователь должен иметь возможность менять язык страницы с русского на английский и наоборот.
  - Пользователь должен иметь возможность связи с магазином.
  - Пользователь должен иметь возможность удалять товары из карзины.
  - Пользователь должен иметь возможность продолжать покупки после добавления товара в карзину.
 
